import { FunctionalComponent } from "../../stencil-public-runtime";
declare type DatePickerInputProps = {
    value: string;
    placeholder: string;
    name: string;
    identifier: string;
    buttonLabel: string;
    inputLabel: string;
    disabled: boolean;
    error: string;
    role: string;
    labelHidden: boolean;
    onClick: (event: MouseEvent) => void;
    onInput: (event: InputEvent) => void;
    onBlur: (event: FocusEvent) => void;
    onFocus: (event: FocusEvent) => void;
    buttonRef: (element: HTMLButtonElement) => void;
    inputRef: (element: HTMLInputElement) => void;
};
export declare const DatePickerInput: FunctionalComponent<DatePickerInputProps>;
export {};
