/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { DuetDatePickerChangeEvent, DuetDatePickerFocusEvent, DuetLanguage } from "./components/duet-date-picker/duet-date-picker";
export namespace Components {
    interface DuetDatePicker {
        /**
          * Makes the date picker input component disabled. This prevents users from being able to interact with the input, and conveys its inactive state to assistive technologies.
         */
        "disabled": boolean;
        /**
          * Display the date picker input in error state along with an error message.
         */
        "error": string;
        /**
          * Hide the calendar modal. Set `moveFocusToButton` to false to prevent focus returning to the date picker's button. Default is true.
         */
        "hide": (moveFocusToButton?: boolean) => Promise<void>;
        /**
          * Adds a unique identifier for the date picker input.
         */
        "identifier": string;
        /**
          * Label for the date picker input.
         */
        "label": string;
        /**
          * Visually hide the label, but still show it to screen readers.
         */
        "labelHidden": boolean;
        /**
          * The currently active language. This setting changes the month/year/day names and button labels as well as all screen reader labels.
         */
        "language": DuetLanguage;
        /**
          * Minimum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD This setting can be used alone or together with the min property.
         */
        "max": string;
        /**
          * Minimum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD. This setting can be used alone or together with the max property.
         */
        "min": string;
        /**
          * Name of the date picker input.
         */
        "name": string;
        /**
          * Defines a specific role attribute for the date picker input.
         */
        "role": string;
        /**
          * Sets focus on the date picker's input. Use this method instead of the global `focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * Show the calendar modal, moving focus to the calendar inside.
         */
        "show": () => Promise<void>;
        /**
          * Date value. Must be in IS0-8601 format: YYYY-MM-DD
         */
        "value": string;
    }
}
declare global {
    interface HTMLDuetDatePickerElement extends Components.DuetDatePicker, HTMLStencilElement {
    }
    var HTMLDuetDatePickerElement: {
        prototype: HTMLDuetDatePickerElement;
        new (): HTMLDuetDatePickerElement;
    };
    interface HTMLElementTagNameMap {
        "duet-date-picker": HTMLDuetDatePickerElement;
    }
}
declare namespace LocalJSX {
    interface DuetDatePicker {
        /**
          * Makes the date picker input component disabled. This prevents users from being able to interact with the input, and conveys its inactive state to assistive technologies.
         */
        "disabled"?: boolean;
        /**
          * Display the date picker input in error state along with an error message.
         */
        "error"?: string;
        /**
          * Adds a unique identifier for the date picker input.
         */
        "identifier"?: string;
        /**
          * Label for the date picker input.
         */
        "label"?: string;
        /**
          * Visually hide the label, but still show it to screen readers.
         */
        "labelHidden"?: boolean;
        /**
          * The currently active language. This setting changes the month/year/day names and button labels as well as all screen reader labels.
         */
        "language"?: DuetLanguage;
        /**
          * Minimum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD This setting can be used alone or together with the min property.
         */
        "max"?: string;
        /**
          * Minimum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD. This setting can be used alone or together with the max property.
         */
        "min"?: string;
        /**
          * Name of the date picker input.
         */
        "name"?: string;
        /**
          * Event emitted the date picker input is blurred.
         */
        "onDuetBlur"?: (event: CustomEvent<DuetDatePickerFocusEvent>) => void;
        /**
          * Event emitted when a date is selected.
         */
        "onDuetChange"?: (event: CustomEvent<DuetDatePickerChangeEvent>) => void;
        /**
          * Event emitted the date picker input is focused.
         */
        "onDuetFocus"?: (event: CustomEvent<DuetDatePickerFocusEvent>) => void;
        /**
          * Defines a specific role attribute for the date picker input.
         */
        "role"?: string;
        /**
          * Date value. Must be in IS0-8601 format: YYYY-MM-DD
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "duet-date-picker": DuetDatePicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "duet-date-picker": LocalJSX.DuetDatePicker & JSXBase.HTMLAttributes<HTMLDuetDatePickerElement>;
        }
    }
}
