import { DuetLocalisedText } from "./types"

const localization: DuetLocalisedText = {
  buttonLabel: "Choose date",
  placeholder: "YYYY-MM-DD",
  selectedDateMessage: "Selected date is",
  prevMonthLabel: "Previous month",
  nextMonthLabel: "Next month",
  monthSelectLabel: "Month",
  yearSelectLabel: "Year",
  closeLabel: "Close window",
  keyboardInstruction: "You can use arrow keys to navigate dates",
  calendarHeading: "Choose a date",
  dayNames: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  monthNames: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  monthNamesShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
}

// const fi: LocalisedText = {
//   buttonLabel: "Valitse päivämäärä",
//   prevMonthLabel: "Edellinen kuukausi",
//   nextMonthLabel: "Seuraava kuukausi",
//   monthSelectLabel: "Kuukausi",
//   yearSelectLabel: "Vuosi",
//   closeLabel: "Sulje ikkuna",
//   keyboardInstruction: "Voit navigoida päivämääriä nuolinäppäimillä",
//   dayLabels: ["Maanantai", "Tiistai", "Keskiviikko", "Torstai", "Perjantai", "Lauantai", "Sunnuntai"],
//   calendarHeading: "Valitse päivämäärä",
//   selected: "Valittu päivämäärä on",
//   placeholder: "pp.kk.vvvv",
//   monthLabels: [
//     "Tammikuu",
//     "Helmikuu",
//     "Maaliskuu",
//     "Huhtikuu",
//     "Toukokuu",
//     "Kesäkuu",
//     "Heinäkuu",
//     "Elokuu",
//     "Syyskuu",
//     "Lokakuu",
//     "Marraskuu",
//     "Joulukuu",
//   ],
//   monthLabelsShort: [
//     "Tammi",
//     "Helmi",
//     "Maalis",
//     "Huhti",
//     "Touko",
//     "Kesä",
//     "Heinä",
//     "Elo",
//     "Syys",
//     "Loka",
//     "Marras",
//     "Joulu",
//   ],
// }

// const sv: LocalisedText = {
//   buttonLabel: "Välj datum",
//   prevMonthLabel: "Föregående månad",
//   nextMonthLabel: "Nästa månad",
//   monthSelectLabel: "Månad",
//   yearSelectLabel: "År",
//   closeLabel: "Stäng fönstret",
//   keyboardInstruction: "Använd piltangenterna för att navigera i kalender",
//   dayLabels: ["Måndag", "Tisdag", "Onsdag", "Torsdag", "Fredag", "Lördag", "Söndag"],
//   calendarHeading: "Välj datum",
//   selected: "Valt datum är",
//   placeholder: "dd.mm.åååå",
//   monthLabels: [
//     "Januari",
//     "Februari",
//     "Mars",
//     "April",
//     "Maj",
//     "Juni",
//     "Juli",
//     "Augusti",
//     "September",
//     "Oktober",
//     "November",
//     "December",
//   ],
//   monthLabelsShort: ["Jan", "Feb", "Mars", "April", "Maj", "Juni", "Juli", "Aug", "Sep", "Okt", "Nov", "Dec"],
// }

export default localization
